### ISSUE TITLE
Not a issue,Need help  if you came through same scenario

### ISSUE THREAD

**Issue by PKS89** [mpalourdio/SpringBootAngularHTML5#1]
I have a SpringBootAngular app, we build angular components separately and put them in "resources/static"folder of SpringBoot project.It is working fine when i start the SpringBoot project.

But My project was access from different parent app hosted in different server when they access our app URL they send user info through request cookie and i am able to see those cookies in my server using Spring GetMapping(*).

My scenario is ,After getting those request cookie we need to server angular component,I have tried below code.However it is not working.
@Controller
public class ViewController {
	@GetMapping("*")
    public String handleTestRequestAll(HttpServletRequest request,HttpServletResponse response){

    	System.out.println("ViewController:*:printing req cookies for all-----------------");
        Cookie[] cookies = request.getCookies();
        if (cookies != null) {
            Arrays.stream(cookies)
                  .forEach(c -> System.out.println(c.getName() + "=" + c.getValue()));
        }
        return "forward:/";   
    }

**Comment by mpalourdio** [comment]
Sorry but this is really not related to this repository. You should definitely post your question on StackOverflow.

Closing, as not related to this repo.
