### ISSUE TITLE
base-href replacement and server context

### ISSUE THREAD

**Issue by roelal** [mpalourdio/SpringBootAngularHTML5#3]
First of all, thanks! Two small notes:
* I see the replacement pattern #base-href#, but I see it used nowhere. index.html has no <base> tag.
* I think the servlet context is not correctly read when this is ran in a tomcat instance. So instead of using the properties directly, use the javax.servlet.ServletContext.

**Comment by mpalourdio** [comment]
Hello,

base href is handled [here](https://github.com/mpalourdio/SpringBootAngularHTML5/blob/77ce76b0fe7d5e5f37d29db085b92344ec980e61/front/angular.json#L61 and [here](https://github.com/mpalourdio/SpringBootAngularHTML5/blob/77ce76b0fe7d5e5f37d29db085b92344ec980e61/front/angular.json#L71) for both ``serve`` and ``build``

The servlet context property is the one handled by the embedded tomcat in Spring Boot. I dropped the tomcat/war support a long time ago ! As you can see, the ``main`` does not extend ``SpringBootServletInitializer`` which is mandatory to package the application as a runnable war.

Anyway, thanks for feedback !

**Comment by mpalourdio** [comment]
And to finish, the property for the context-path is the good one, see [this class](https://github.com/spring-projects/spring-boot/blob/bf0523819840e097bde0cbd3497a5bf02f6df8f8/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java#L229).

I use this configuration in production for a long time now !
