### ISSUE TITLE
Static html serve issue

### ISSUE THREAD

**Issue by bhikyagolu** [mpalourdio/SpringBootAngularHTML5#6]
Hey this repo is really awosome ..

This helped me to serve angular from spring boot with html5 url

but this broke my static files from public folder
i have graph html files and corrospoding js files 
i request these html directly by passing URL params which are picked by js to render those graphs .. this i needed to make these to png and send thro email
stuck on these public folder access ... previously all was well

you help will be appreciated

**Comment by mpalourdio** [comment]
Closing as this is an integration problem for a particular use-case, and in any way a bug related with the source code avalaible in this repository. Feel free to post on stackoverflow for any spring/angular related help.
