### ISSUE TITLE
Application does not load on chrome and safari

### ISSUE THREAD

**Issue by etasens** [mpalourdio/SpringBootAngularHTML5#9]
Hello the application does not load on Chrome/Safari and keeps on showing "Loading.." message. Nor do I see any errors in console. Am I missing something here?

Works great on Firefox though.

**Comment by mpalourdio** [comment]
Hello,

That's weird. What's the browser console output ?

**Comment by etasens** [comment]
There is no console output. Seems like index.html loaded and the angular component did not load. Screen just shows loading message in index.html. 

This is using the generated non snapshot jar after mvn install -Pfront. Started with java -jar command.



Regards

Kedar Kulkarni
Co-founder, CTO | Etasens Technologies
www.etasens.com | +91-8800342200 | Skype - kedar@etasens.com


---- On Fri, 22 Mar 2019 17:31:28 +0530 notifications@github.com wrote ----



Hello,

That's weird. What's the browser console output ?

**Comment by mpalourdio** [comment]
Is this a fresh clone or have you modified things before running ? Take a look at the network tab in chrome too. And please copy paste here the source code of the page you see in your browser.

**Comment by etasens** [comment]
I have updated application.properties 

-server.servlet.context-path=/my-context/path
+server.servlet.context-path=/

This works in firefox but not in chrome/safari

Source Code Of Page on Chrome

```
<!doctype html>
<html>
<head><base href="//">
    <meta charset="utf-8">
    <title>Front</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="static/favicon.ico">
<link rel="stylesheet" href="static/styles.94b567748199194bd8a6.css"></head>
<body>
<app-root>Loading...</app-root>
<script type="text/javascript" src="static/runtime.b66554d3304a15c027d4.js"></script><script type="text/javascript" src="static/polyfills.5a726f9f73c3867f9d67.js"></script><script type="text/javascript" src="static/main.7f4e9e426f39d5b2e8d8.js"></script></body>
</html>
```

Network Tab on Chrome
<img width="1423" alt="Screen Shot 2019-03-22 at 7 47 52 PM" src="https://user-images.githubusercontent.com/39612055/54829007-7c642f00-4cdb-11e9-9dea-b68af90d97b3.png">

**Comment by mpalourdio** [comment]
Oh, I see, It does not handle the case where context-path is '/'. Try this :

```diff
-server.servlet.context-path=/
+server.servlet.context-path=
```

Anyway, '/' is not a valid context path. But I will fix this anytime soon in more gracefully way.

**Comment by mpalourdio** [comment]
Fixed in https://github.com/mpalourdio/SpringBootAngularHTML5/commit/ccd30a4a93454d2f2d22d08a7de871f692c0ca74.

**Comment by etasens** [comment]
Thank you for the quick fix and response!
